title: NewsFlow
description: A modern news source discovery and management app
theme: jekyll-theme-minimal
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
